version: '3'
services:

  # Frontend

  frontend:
    build: 
      context: ./Frontend-React
      args:
        - REACT_APP_BACKEND_GRAPHQL=${REACT_APP_BACKEND_GRAPHQL}
        - REACT_APP_BACKEND_UPLOAD =${REACT_APP_BACKEND_UPLOAD} 
        - REACT_APP_FRONTEND=${REACT_APP_FRONTEND} 

    container_name: Frontend
    ports:
      - 80:80

  # Backend Services

  backend:
    build: ./Backend-GraphQL
    container_name: Backend
    ports:
      - 8080:8080
      - 8081:8081